### ISSUE TITLE
How to set the filename?

### ISSUE THREAD

**Issue by jdinuncio** [collective/plone.jsonapi.routes#38]
This is **not** a bug, but I was wondering how could I set the name of a file during the upload. I tried with filename, __name__, name, fileName, ... (I'm not talking about the id or title of the Plone object, but the name associated to the file, with the blob).

I think adding an example for file upload in the documentation would be helpful.

**Comment by ramonski** [comment]
@jdinuncio: You are right. It is currently not possible to set the filename by the API. This is because the filename is not a field of the content and get simply ignored. The missing filename unfortunately also results in the wrong mime type of the file as described in #36 
The only way to handle this issue would be to introduce the `filename` as a valid key for the API.

**Comment by ramonski** [comment]
@jdinuncio: You can now pass in the `filename` or even the `mimetype` to control this setting. If no filename was found in theJSON  data, the datamanager will fall back to the `id` and then to the `title`. The latter two cases would need to provide a file extension, e.g. `foo.docx` to guess the mime type correctly.

**Comment by ramonski** [comment]
mplemented in 0.7

**Comment by reduc-uc** [comment]
Thank you very much, ramonski!
