### ISSUE TITLE
complete=True does not give complete fields

### ISSUE THREAD

**Issue by sunew** [collective/plone.jsonapi.routes#63]
http://localhost:8080/site/@@API/plone/api/1.0/documents/8e34c2f764cf48108e5524d1bf83a4b2?complete=True

Same result as 
http://localhost:8080/site/@@API/plone/api/1.0/documents/8e34c2f764cf48108e5524d1bf83a4b2

Especially - the body text field and transitions are missing.

(Plone 5)

**Comment by ramonski** [comment]
The first request contains already the UID, thus it is equivalent to `complete=True`.

I change the behavior of the workflow info because of performance reasons, see:
http://plonejsonapiroutes.readthedocs.org/en/latest/api.html#parameters

You have to add now `?workflow=yes&complete=yes` if you would like to have these information on the returned results.

That the body text is missing is new for me. Can you provide more details on that?
